# Bài tập về nhà: Singular Value Decomposition (SVD)

Bài tập gồm 2 câu:

1. Phân rã một ma trận có rank thấp bằng SVD.
2. Chọn số thành phần k cho Truncated SVD dựa trên tỷ lệ năng lượng.

---

# Câu 1. Phân rã ma trận

Cho ma trận:

$$
A=
\begin{bmatrix}
1 & 0 & 1\\
0 & 1 & 1\\
1 & 0 & 1\\
0 & 1 & 1
\end{bmatrix}
\in\mathbb{R}^{4\times3}
$$

## Yêu cầu

1. Chứng minh các cột của $A$ phụ thuộc tuyến tính và xác định $\operatorname{rank}(A)$.
2. Tính $A^\top A$.
3. Tìm các eigenvalues và eigenvectors trực chuẩn của $A^\top A$.
4. Sắp xếp $\lambda_1\geq\lambda_2\geq\lambda_3$.
5. Tính các singular values $\sigma_i=\sqrt{\lambda_i}$.
6. Xác định các right singular vectors $v_1,v_2,v_3$.
7. Với mỗi $\sigma_i>0$, tính $u_i=Av_i/\sigma_i$.
8. Bổ sung các vector trực chuẩn còn thiếu để viết Full SVD:

$$
A=U\Sigma V^\top
$$

với:

$$
U\in\mathbb{R}^{4\times4},\qquad
\Sigma\in\mathbb{R}^{4\times3},\qquad
V^\top\in\mathbb{R}^{3\times3}
$$

9. Viết Reduced SVD:

$$
A=U_r\Sigma_rV_r^\top
$$

10. Ghi rõ kích thước của $U_r,\Sigma_r,V_r^\top$.
11. Kiểm tra $U^\top U=I$, $V^\top V=I$ và $U\Sigma V^\top=A$.
12. Giải thích:
   - Vì sao có một singular value bằng 0?
   - Singular vector tương ứng với singular value bằng 0 liên hệ thế nào với null space của $A$?
   - Vì sao Reduced SVD vẫn tái tạo chính xác $A$?

> Phải trình bày các bước tính toán. Có thể dùng Python để kiểm tra kết quả cuối cùng.

---

# Câu 2. Chọn k cho Truncated SVD bằng tỷ lệ năng lượng

Một ma trận dữ liệu $X$ có các singular values:

$$
\sigma_1=12,\qquad
\sigma_2=5,\qquad
\sigma_3=3,\qquad
\sigma_4=1
$$

Ma trận xấp xỉ hạng $k$:

$$
X_k=\sum_{i=1}^{k}\sigma_i u_i v_i^\top
$$

## Yêu cầu

1. Xác định rank của $X$.
2. Tính tổng năng lượng:

$$
E_{\text{total}}=\sum_{i=1}^{4}\sigma_i^2
$$

3. Với $k=1,2,3,4$, tính:

$$
R(k)=
\frac{\sum_{i=1}^{k}\sigma_i^2}
{\sum_{i=1}^{4}\sigma_i^2}
$$

4. Hoàn thành bảng:

| $k$ | Năng lượng giữ lại | Tỷ lệ $R(k)$ |
|---:|---:|---:|
| 1 |  |  |
| 2 |  |  |
| 3 |  |  |
| 4 |  |  |

5. Tìm $k$ nhỏ nhất để giữ ít nhất:
   - 80% năng lượng.
   - 90% năng lượng.
   - 95% năng lượng.
   - 99% năng lượng.

6. Với $k=1,2,3$, tính:

$$
\|X-X_k\|_F=
\sqrt{\sum_{i=k+1}^{4}\sigma_i^2}
$$

7. Hoàn thành bảng:

| $k$ | $R(k)$ | $\|X-X_k\|_F$ |
|---:|---:|---:|
| 1 |  |  |
| 2 |  |  |
| 3 |  |  |

8. Giả sử $\sigma_4$ chủ yếu biểu diễn nhiễu. Chọn $k$ phù hợp và giải thích.
9. Trả lời:
   - Vì sao singular values phải được sắp xếp giảm dần?
   - Giữ càng nhiều singular values có phải lúc nào cũng tốt hơn không?
   - Sự đánh đổi giữa tỷ lệ năng lượng và mức độ nén dữ liệu là gì?

---

# Yêu cầu nộp bài

Nộp một trong hai file:

```text
svd_homework.ipynb
```

hoặc:

```text
svd_homework.pdf
```

## Quy định

- Câu 1 phải trình bày đầy đủ các bước phân rã.
- Câu 2 phải ghi rõ phép tính năng lượng và cách chọn $k$.
- Không chỉ ghi đáp án cuối cùng.
- Có thể dùng Python để kiểm tra nhưng phải giải thích kết quả.

---

In [1]:
import numpy as np
A = np.array([
    [1,0,1],
    [0,1,1],
    [1,0,1],
    [0,1,1]
], dtype=float)
print("A =")
print(A)

A =
[[1. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 1.]]



Ba cột của ma trận là

a_1=
\begin{bmatrix}
1\\0\\1\\0
\end{bmatrix},

a_2=
\begin{bmatrix}
0\\1\\0\\1
\end{bmatrix},

a_3=
\begin{bmatrix}
1\\1\\1\\1
\end{bmatrix}

Ta có

a_3=a_1+a_2

nên các cột phụ thuộc tuyến tính.

Do đó:

# rank(A)=2

In [2]:
print("Rank(A) =", np.linalg.matrix_rank(A))

Rank(A) = 2


# 2. Tính \(A^T*A\)

Ta có

A=
\begin{bmatrix}
1&0&1\\
0&1&1\\
1&0&1\\
0&1&1
\end{bmatrix}

Khi đó

A^T=
\begin{bmatrix}
1&0&1&0\\
0&1&0&1\\
1&1&1&1
\end{bmatrix}

Tính từng phần tử:

### Hàng 1

(1,1)=1^2+0^2+1^2+0^2=2

(1,2)=1* 0+1* 0+1* 0+1* 0 =0

(1,3)=1* 1+1* 0+1* 1+1*0=2

### Hàng 2

(2,1)=0

(2,2)=0^2+1^2+0^2+1^2=2

(2,3)=0* 1+1* 1+0* 1 +1* 1=2

### Hàng 3

(3,1)=2

(3,2)=2

(3,3)=1^2+1^2+1^2+1^2=4

Do đó

A^TA=
\begin{bmatrix}
2&0&2\\
0&2&2\\
2&2&4
\end{bmatrix}

In [3]:
A = np.array([
    [1,0,1],
    [0,1,1],
    [1,0,1],
    [0,1,1]
], dtype=float)
print(A.T @ A)

[[2. 0. 2.]
 [0. 2. 2.]
 [2. 2. 4.]]


# 3. Tìm Eigenvalues và Eigenvectors của \(A^TA\)

Ta có

A^TA=
\begin{bmatrix}
2&0&2\\
0&2&2\\
2&2&4
\end{bmatrix}.

Các eigenvalues được xác định từ phương trình đặc trưng

det(A^TA-\lambda I)=0.

Ta có

A^TA-lambda I=
\begin{bmatrix}
2-\lambda&0&2\\
0&2-\lambda&2\\
2&2&4-\lambda
\end{bmatrix}.

Khai triển định thức theo hàng đầu:

\begin{aligned}
\det(A^TA-\lambda I)
&=(2-\lambda)
\begin{vmatrix}
2-\lambda&2\\
2&4-\lambda
\end{vmatrix}
+2
\begin{vmatrix}
0&2-\lambda\\
2&2
\end{vmatrix}.
\end{aligned}

Tính các định thức con

\begin{aligned}
\begin{vmatrix}
2-\lambda&2\\
2&4-\lambda
\end{vmatrix}
&=(2-\lambda)(4-\lambda)-4 \\
&=\lambda^2-6\lambda+4,
\end{aligned}

và
\begin{aligned}
\begin{vmatrix}
0&2-\lambda\\
2&2
\end{vmatrix}
=-2(2-\lambda).
\end{aligned}

Suy ra

\begin{aligned}
\det(A^TA-\lambda I)
&=(2-\lambda)(\lambda^2-6\lambda+4)-4(2-\lambda)\\
&=(2-\lambda)(\lambda^2-6\lambda)\\
&=-\lambda(2-\lambda)(6-\lambda).
\end{aligned}

Do đó

lambda1=6, lambda2=2, lambda3=0

### Eigenvector ứng với \(\lambda=6\)

Ta giải hệ

(A^TA-6I)x=0.

Ta có
\begin{aligned}
A^TA-6I=
\begin{bmatrix}
-4&0&2\\
0&-4&2\\
2&2&-2
\end{bmatrix}.
\end{aligned}
Đặt

\begin{aligned}
x=
\begin{bmatrix}
x_1\\
x_2\\
x_3
\end{bmatrix}.
\end{aligned}

Khi đó

\begin{aligned}
\begin{bmatrix}
-4&0&2\\
0&-4&2\\
2&2&-2
\end{bmatrix}

\begin{bmatrix}
x_1\\
x_2\\
x_3
\end{bmatrix}
=
\begin{bmatrix}
0\\
0\\
0
\end{bmatrix}
\end{aligned}

tương đương hệ phương trình

\begin{cases}
-4x_1+2x_3=0,\\
-4x_2+2x_3=0,\\
2x_1+2x_2-2x_3=0.
\end{cases}

Từ phương trình thứ nhất,

x_3=2x_1.

Từ phương trình thứ hai,

x_3=2x_2.

Suy ra

x_1=x_2.

Đặt

x_1=x_2=t,

thì

x_3=2t.

Do đó nghiệm tổng quát là

\begin{aligned}
x
=
t
\begin{bmatrix}
1\\
1\\
2
\end{bmatrix}.
\end{aligned}

Chọn \(t=1\), ta được một eigenvector

\begin{aligned}
\begin{bmatrix}
1\\
1\\
2
\end{bmatrix}.
\end{aligned}

Chuẩn hóa:

\begin{aligned}
\left\|
\begin{bmatrix}
1\\
1\\
2
\end{bmatrix}
\right\|
=
\sqrt{1^2+1^2+2^2}
=
\sqrt6.
\end{aligned}

Do đó

\begin{aligned}
\boxed{
v_1=
\frac1{\sqrt6}
\begin{bmatrix}
1\\
1\\
2
\end{bmatrix}
}
\end{aligned}

---

### Eigenvector ứng với \(\lambda=2\)

Ta giải

(A^TA-2I)x=0.

Ta có

A^TA-2I=
\begin{bmatrix}
0&0&2\\
0&0&2\\
2&2&2
\end{bmatrix}.

Khi đó

\begin{aligned}
\begin{bmatrix}
0&0&2\\
0&0&2\\
2&2&2
\end{bmatrix}
\begin{bmatrix}
x_1\\
x_2\\
x_3
\end{bmatrix}
=
\begin{bmatrix}
0\\
0\\
0
\end{bmatrix}
\end{aligned}

tương đương

\begin{cases}
2x_3=0,\\
2x_3=0,\\
2x_1+2x_2+2x_3=0.
\end{cases}

Suy ra

x_3=0.

Thay vào phương trình cuối,

2x_1+2x_2=0,

hay

x_1=-x_2.

Đặt

x_1=t,

thì

x_2=-t.

Do đó

\begin{aligned}
x
=
t
\begin{bmatrix}
1\\
-1\\
0
\end{bmatrix}.
\end{aligned}

Chọn \(t=1\),

\begin{bmatrix}
1\\
-1\\
0
\end{bmatrix}

là một eigenvector.

Chuẩn hóa:

\begin{aligned}
\left\|
\begin{bmatrix}
1\\
-1\\
0
\end{bmatrix}
\right\|
=
\sqrt2.
\end{aligned}

Vậy

\begin{aligned}
\boxed{
v_2=
\frac1{\sqrt2}
\begin{bmatrix}
1\\
-1\\
0
\end{bmatrix}
}
\end{aligned}

---

### Eigenvector ứng với \(\lambda=0\)

Ta giải

A^TAx=0.

Tức là

\begin{aligned}
\begin{bmatrix}
2&0&2\\
0&2&2\\
2&2&4
\end{bmatrix}
\begin{bmatrix}
x_1\\
x_2\\
x_3
\end{bmatrix}
=
\begin{bmatrix}
0\\
0\\
0
\end{bmatrix}.
\end{aligned}

Suy ra hệ


\begin{cases}
2x_1+2x_3=0,\\
2x_2+2x_3=0,\\
2x_1+2x_2+4x_3=0.
\end{cases}


Chia cả ba phương trình cho 2,

\begin{cases}
x_1+x_3=0,\\
x_2+x_3=0,\\
x_1+x_2+2x_3=0.
\end{cases}

Từ hai phương trình đầu,

\begin{aligned}
x_1=-x_3,\qquad
x_2=-x_3.
\end{aligned}

Đặt

x_3=t,

thì

\begin{aligned}
x_1=-t,\qquad
x_2=-t.
\end{aligned}

Do đó

\begin{aligned}
x
=
t
\begin{bmatrix}
-1\\
-1\\
1
\end{bmatrix}.
\end{aligned}

Chọn \(t=1\),

\begin{bmatrix}
-1\\
-1\\
1
\end{bmatrix}

là một eigenvector.

Chuẩn hóa:

\begin{aligned}
\left\|
\begin{bmatrix}
-1\\
-1\\
1
\end{bmatrix}
\right\|
=
\sqrt3.
\end{aligned}

Suy ra

\begin{aligned}
\boxed{
v_3=
\frac1{\sqrt3}
\begin{bmatrix}
-1\\
-1\\
1
\end{bmatrix}
}
\end{aligned}

### Kết luận

Ba eigenvector trực chuẩn của \(A^TA\) là

\begin{aligned}
\boxed{
v_1=
\frac1{\sqrt6}
\begin{bmatrix}
1\\
1\\
2
\end{bmatrix},
\qquad
v_2=
\frac1{\sqrt2}
\begin{bmatrix}
1\\
-1\\
0
\end{bmatrix},
\qquad
v_3=
\frac1{\sqrt3}
\begin{bmatrix}
-1\\
-1\\
1
\end{bmatrix}.
}
\end{aligned}

In [5]:
A = np.array([
    [1,0,1],
    [0,1,1],
    [1,0,1],
    [0,1,1]
], float)
eigvals, eigvecs = np.linalg.eig(A.T @ A)

print(np.round(eigvals, 6))
print(np.round(eigvecs, 6))

[ 6.  2. -0.]
[[-0.408248 -0.707107 -0.57735 ]
 [-0.408248  0.707107 -0.57735 ]
 [-0.816497 -0.        0.57735 ]]


## 4. Tính các Left Singular Vectors

Theo định nghĩa,

\begin{aligned}
u_i=\frac{Av_i}{\sigma_i},\qquad \sigma_i>0.
\end{aligned}

Do đó chỉ cần tính \(u_1\) và \(u_2\).

---

### Tính \(u_1\)

Ta có

\begin{aligned}
v_1=
\frac1{\sqrt6}
\begin{bmatrix}
1\\
1\\
2
\end{bmatrix},
\qquad
\sigma_1=\sqrt6.
\end{aligned}

Trước hết tính

\begin{aligned}
Av_1
=
\frac1{\sqrt6}
A
\begin{bmatrix}
1\\
1\\
2
\end{bmatrix}.
\end{aligned}

Ta có

\begin{aligned}
A
\begin{bmatrix}
1\\
1\\
2
\end{bmatrix}
=
\begin{bmatrix}
1\cdot1+0\cdot1+1\cdot2\\
0\cdot1+1\cdot1+1\cdot2\\
1\cdot1+0\cdot1+1\cdot2\\
0\cdot1+1\cdot1+1\cdot2
\end{bmatrix}
=
\begin{bmatrix}
3\\
3\\
3\\
3
\end{bmatrix}.
\end{aligned}

Do đó

\begin{aligned}
Av_1
=
\frac1{\sqrt6}
\begin{bmatrix}
3\\
3\\
3\\
3
\end{bmatrix}.
\end{aligned}

Suy ra

\begin{aligned}
u_1
=
\frac{Av_1}{\sqrt6}
=
\frac1{6}
\begin{bmatrix}
3\\
3\\
3\\
3
\end{bmatrix}
=
\frac12
\begin{bmatrix}
1\\
1\\
1\\
1
\end{bmatrix}.
\end{aligned}

---

### Tính \(u_2\)

Ta có

\begin{aligned}
v_2=
\frac1{\sqrt2}
\begin{bmatrix}
1\\
-1\\
0
\end{bmatrix},
\qquad
\sigma_2=\sqrt2.
\end{aligned}

Tính

\begin{aligned}
Av_2
=
\frac1{\sqrt2}
A
\begin{bmatrix}
1\\
-1\\
0
\end{bmatrix}.
\end{aligned}

Ta được

\begin{aligned}
A
\begin{bmatrix}
1\\
-1\\
0
\end{bmatrix}
=
\begin{bmatrix}
1\\
-1\\
1\\
-1
\end{bmatrix}.
\end{aligned}

Do đó

\begin{aligned}
Av_2
=
\frac1{\sqrt2}
\begin{bmatrix}
1\\
-1\\
1\\
-1
\end{bmatrix}.
\end{aligned}

Suy ra

\begin{aligned}
u_2
=
\frac{Av_2}{\sqrt2}
=
\frac12
\begin{bmatrix}
1\\
-1\\
1\\
-1
\end{bmatrix}.
\end{aligned}


Vậy

\begin{aligned}
\boxed{
u_1=
\frac12
\begin{bmatrix}
1\\
1\\
1\\
1
\end{bmatrix},
\qquad
u_2=
\frac12
\begin{bmatrix}
1\\
-1\\
1\\
-1
\end{bmatrix}.
}
\end{aligned}

---

## 5. Viết Full SVD

Do
\begin{aligned}
\operatorname{rank}(A)=2,
\end{aligned}

nên chỉ có hai left singular vectors được xác định từ công thức trên.

Bổ sung thêm hai vector trực chuẩn

\begin{aligned}
u_3=
\frac1{\sqrt2}
\begin{bmatrix}
1\\
0\\
-1\\
0
\end{bmatrix},
\qquad
u_4=
\frac1{\sqrt2}
\begin{bmatrix}
0\\
1\\
0\\
-1
\end{bmatrix}.
\end{aligned}

Khi đó

\begin{aligned}
U=
\begin{bmatrix}
\frac12&\frac12&\frac1{\sqrt2}&0\\
\frac12&-\frac12&0&\frac1{\sqrt2}\\
\frac12&\frac12&-\frac1{\sqrt2}&0\\
\frac12&-\frac12&0&-\frac1{\sqrt2}
\end{bmatrix}.
\end{aligned}

Ma trận

\begin{aligned}
\Sigma=
\begin{bmatrix}
\sqrt6&0&0\\
0&\sqrt2&0\\
0&0&0\\
0&0&0
\end{bmatrix}.
\end{aligned}

Ma trận

\begin{aligned}
V=
\begin{bmatrix}
\dfrac1{\sqrt6}&\dfrac1{\sqrt2}&-\dfrac1{\sqrt3}\\
\dfrac1{\sqrt6}&-\dfrac1{\sqrt2}&-\dfrac1{\sqrt3}\\
\dfrac2{\sqrt6}&0&\dfrac1{\sqrt3}
\end{bmatrix}.
\end{aligned}

Do đó

\begin{aligned}
\boxed{
A=U\Sigma V^T.
}
\end{aligned}

---

## 5. Reduced SVD

Vì chỉ có hai singular value khác 0 nên

\begin{aligned}
U_r=
\begin{bmatrix}
u_1&u_2
\end{bmatrix},
\end{aligned}

\begin{aligned}
\Sigma_r=
\begin{bmatrix}
\sqrt6&0\\
0&\sqrt2
\end{bmatrix},
\end{aligned}

\begin{aligned}
V_r=
\begin{bmatrix}
v_1&v_2
\end{bmatrix}.
\end{aligned}

Do đó

\begin{aligned}
\boxed{
A=U_r\Sigma_rV_r^T.
}
\end{aligned}

---

## 6. Kích thước

\begin{aligned}
U_r\in\mathbb{R}^{4\times2},
\end{aligned}

\begin{aligned}
\Sigma_r\in\mathbb{R}^{2\times2},
\end{aligned}

\begin{aligned}
V_r^T\in\mathbb{R}^{2\times3}.
\end{aligned}

---

## 7. Kiểm tra

Các cột của \(U\) trực chuẩn nên

\begin{aligned}
U^TU=I_4.
\end{aligned}

Các cột của \(V\) trực chuẩn nên

\begin{aligned}
V^TV=I_3.
\end{aligned}

Ngoài ra,

\begin{aligned}
U\Sigma V^T=A.
\end{aligned}

Do đó phép phân rã SVD là chính xác.

---

## 8. Giải thích

### Vì sao có một singular value bằng 0?

Do

\begin{aligned}
\operatorname{rank}(A)=2<3.
\end{aligned}

Số singular value khác 0 luôn bằng hạng của ma trận, nên singular value còn lại bằng 0.

---

### Singular vector ứng với singular value bằng 0 liên hệ thế nào với Null Space?

Nếu

\begin{aligned}
\sigma=0,
\end{aligned}

thì

\begin{aligned}
A^TAv=0.
\end{aligned}

Suy ra

\begin{aligned}
Av=0.
\end{aligned}

Do đó eigenvector

\begin{aligned}
v_3=
\frac1{\sqrt3}
\begin{bmatrix}
-1\\
-1\\
1
\end{bmatrix}
\end{aligned}

là một cơ sở trực chuẩn của Null Space của \(A\).

---

### Vì sao Reduced SVD vẫn tái tạo chính xác \(A\)?

Reduced SVD chỉ giữ các singular value khác 0.

Các singular value bằng 0 không đóng góp vào tổng

\begin{aligned}
A=\sum_i\sigma_i u_i v_i^T,
\end{aligned}

vì

\begin{aligned}
0\cdot u_i v_i^T=0.
\end{aligned}

Do đó Reduced SVD vẫn biểu diễn chính xác ma trận \(A\).

In [8]:
np.set_printoptions(suppress=True, precision=6)
U, S, VT = np.linalg.svd(A)
print("Singular values:")
print(S)

Sigma = np.zeros((4,3))
Sigma[:3,:3] = np.diag(S)
A_new = U @ Sigma @ VT
print(A_new)
print("\nEqual:", np.allclose(A, A_new))

Singular values:
[2.44949  1.414214 0.      ]
[[ 1.  0.  1.]
 [-0.  1.  1.]
 [ 1.  0.  1.]
 [-0.  1.  1.]]

Equal: True


---
## Câu 2. Chọn k cho Truncated SVD bằng tỷ lệ năng lượng

## 1. Xác định rank của \(X\)

Rank của ma trận bằng số singular values khác 0.

Vì

\begin{aligned}
\sigma_1=12,\quad
\sigma_2=5,\quad
\sigma_3=3,\quad
\sigma_4=1
\end{aligned}

đều khác 0 nên

\begin{aligned}
\boxed{\operatorname{rank}(X)=4.}
\end{aligned}


## 2. Tính tổng năng lượng

Tổng năng lượng được tính theo công thức

\begin{aligned}
E_{\text{total}}
=
\sum_{i=1}^{4}\sigma_i^2.
\end{aligned}

Ta có

\begin{aligned}
\begin{aligned}
E_{\text{total}}
&=12^2+5^2+3^2+1^2\\
&=144+25+9+1\\
&=179.
\end{aligned}
\end{aligned}

Vậy

\begin{aligned}
\boxed{E_{\text{total}}=179.}
\end{aligned}


## 3. Tính tỷ lệ năng lượng \(R(k)\)

### Với \(k=1\)

Năng lượng giữ lại

\begin{aligned}
E_1=12^2=144.
\end{aligned}

Do đó

\begin{aligned}
R(1)
=
\frac{144}{179}
\approx0.8045
=
80.45\%.
\end{aligned}


### Với \(k=2\)

Năng lượng giữ lại

\begin{aligned}
E_2
=
12^2+5^2
=
144+25
=
169.
\end{aligned}

Do đó

\begin{aligned}
R(2)
=
\frac{169}{179}
\approx0.9441
=
94.41\%.
\end{aligned}


### Với \(k=3\)

Năng lượng giữ lại

\begin{aligned}
E_3
=
144+25+9
=
178.
\end{aligned}

Do đó

\begin{aligned}
R(3)
=
\frac{178}{179}
\approx0.9944
=
99.44\%.
\end{aligned}


### Với \(k=4\)

Năng lượng giữ lại

\begin{aligned}
E_4
=
179.
\end{aligned}

Do đó

\begin{aligned}
R(4)
=
\frac{179}{179}
=
1
=
100\%.
\end{aligned}


## 4. Bảng tỷ lệ năng lượng

| \(k\) | Năng lượng giữ lại | \(R(k)\) |
|:---:|:---:|:---:|
|1|144|80.45%|
|2|169|94.41%|
|3|178|99.44%|
|4|179|100%|


## 5. Chọn \(k\)

### Giữ ít nhất 80%

\begin{aligned}
R(1)=80.45\%.
\end{aligned}

Vậy

\begin{aligned}
\boxed{k=1.}
\end{aligned}


### Giữ ít nhất 90%

\begin{aligned}
R(1)=80.45\%<90\%
\end{aligned}

\begin{aligned}
R(2)=94.41\%>90\%.
\end{aligned}

Do đó

\begin{aligned}
\boxed{k=2.}
\end{aligned}


### Giữ ít nhất 95%

\begin{aligned}
R(2)=94.41\%<95\%
\end{aligned}

\begin{aligned}
R(3)=99.44\%>95\%.
\end{aligned}

Do đó

\begin{aligned}
\boxed{k=3.}
\end{aligned}


### Giữ ít nhất 99%

\begin{aligned}
R(3)=99.44\%>99\%.
\end{aligned}

Do đó

\begin{aligned}
\boxed{k=3.}
\end{aligned}


## 6. Sai số Frobenius

Theo định lý Eckart–Young,

\begin{aligned}
\|X-X_k\|_F
=
\sqrt{\sum_{i=k+1}^{4}\sigma_i^2}.
\end{aligned}

### Với \(k=1\)

\begin{aligned}
\|X-X_1\|_F
&=
\sqrt{5^2+3^2+1^2}\\
&=
\sqrt{25+9+1}\\
&=
\sqrt{35}\\
&\approx5.916.
\end{aligned}


### Với \(k=2\)

\begin{aligned}
\|X-X_2\|_F
&=
\sqrt{3^2+1^2}\\
&=
\sqrt{10}\\
&\approx3.162.
\end{aligned}


### Với \(k=3\)

\begin{aligned}
\|X-X_3\|_F
&=
\sqrt{1^2}\\
&=1.
\end{aligned}

## 7. Bảng kết quả

| \(k\) | \(R(k)\) | \(\|X-X_k\|_F\) |
|:---:|:---:|:---:|
|1|80.45%|5.916|
|2|94.41%|3.162|
|3|99.44%|1|


## 8. Chọn \(k\)

Giả sử

\begin{aligned}
\sigma_4
\end{aligned}

chủ yếu biểu diễn nhiễu thì không nên giữ singular value này.

Khi đó chọn

\begin{aligned}
\boxed{k=3.}
\end{aligned}

Lý do:

- Giữ lại 99.44% năng lượng.
- Loại bỏ thành phần nhiễu.
- Giảm kích thước dữ liệu nhưng vẫn bảo toàn gần như toàn bộ thông tin.


## 9. Giải thích

### Vì sao singular values phải sắp xếp giảm dần?

Các singular values biểu diễn lượng thông tin (năng lượng) mà mỗi thành phần đóng góp.

Sắp xếp giảm dần giúp các thành phần quan trọng nhất được giữ lại trước, từ đó dễ dàng lựa chọn số chiều \(k\).


### Giữ càng nhiều singular values có phải luôn tốt hơn không?

Không.

Giữ quá nhiều singular values có thể:

- làm giảm hiệu quả nén dữ liệu;
- giữ lại cả thành phần nhiễu;
- tăng chi phí lưu trữ và tính toán.

Do đó cần lựa chọn \(k\) phù hợp thay vì luôn giữ tất cả.


### Sự đánh đổi giữa tỷ lệ năng lượng và mức độ nén dữ liệu

Nếu chọn \(k\) nhỏ:

- dữ liệu được nén nhiều hơn;
- tiết kiệm bộ nhớ và thời gian tính toán;
- nhưng mất nhiều thông tin hơn.

Nếu chọn \(k\) lớn:

- giữ được nhiều thông tin hơn;
- sai số nhỏ hơn;
- nhưng khả năng nén giảm.

Vì vậy cần cân bằng giữa độ chính xác và mức độ nén tùy theo mục đích sử dụng.

In [9]:

sigma = np.array([12, 5, 3, 1], dtype=float)
energy = np.sum(sigma**2)
print("Total energy =", energy)
for k in range(1, 5):
    retained = np.sum(sigma[:k]**2)
    ratio = retained / energy
    print(f"k={k}: Energy={retained}, Ratio={ratio:.4%}")
for k in range(1, 4):
    error = np.sqrt(np.sum(sigma[k:]**2))
    print(f"k={k}: ||X-X{k}||_F = {error:.6f}")

Total energy = 179.0
k=1: Energy=144.0, Ratio=80.4469%
k=2: Energy=169.0, Ratio=94.4134%
k=3: Energy=178.0, Ratio=99.4413%
k=4: Energy=179.0, Ratio=100.0000%
k=1: ||X-X1||_F = 5.916080
k=2: ||X-X2||_F = 3.162278
k=3: ||X-X3||_F = 1.000000
